#ifndef KETTLE_VERSION_H
#define KETTLE_VERSION_H

#include "kettle/core/defines.h"

#define KETTLE_VERSION_MAJOR 0
#define KETTLE_VERSION_MINOR 2
#define KETTLE_VERSION_PATCH 0

#define KETTLE_VERSION \
    KETTLE_STRINGIFY(KETTLE_VERSION_MAJOR) \
    "." KETTLE_STRINGIFY(KETTLE_VERSION_MINOR) "." KETTLE_STRINGIFY(KETTLE_VERSION_PATCH)

KETTLE_NODISCARD const char *kettle_version(void);

#endif
